import type { Lesson, LearningPassion } from './types.ts'
type Row = [string, string, string, string, string, string, string, string]
function rows(passion: LearningPassion, data: Row[]): Lesson[] {
  return data.map((r, i) => ({
    id: `learn-v1-${passion}-${i + 1}`,
    revision: 1,
    passion,
    number: i + 1,
    level: Math.floor(i / 4),
    title: r[0],
    goal: r[1],
    teaching: r[2].split('|'),
    example: r[3],
    guided: r[4],
    practice: r[5],
    checklist: r[6].split('|'),
    visual: r[7],
    tasks: [],
  }))
}
export const DRAW_LESSONS = rows('dessin', [
  [
    'Prendre en main son trait',
    'Tracer avec intention et utiliser les outils.',
    'Choisis un trait fin pour construire, plus épais pour affirmer un contour.|Trace des gestes courts au doigt ; le zoom aide pour les détails.|La gomme retire, Annuler revient au geste précédent : explore sans crainte.',
    'Un trait hésitant peut devenir une courbe fluide en préparant son trajet avant de toucher la feuille.',
    'Relie les points du modèle, puis trace trois courbes en un seul geste chacune.',
    'Dessine une feuille et son contour sans repères. Recommence en variant l’épaisseur.',
    'Mes traits ont un départ et une arrivée choisis|J’ai essayé la gomme et Annuler|Je distingue construction et contour',
    'trait',
  ],
  [
    'Voir les formes simples',
    'Décomposer un objet avant de le détailler.',
    'Observe sa silhouette générale avant les petits détails.|Une tasse associe un cylindre et une anse ; une lampe combine plusieurs volumes.|Les formes sont des outils de construction : elles peuvent se chevaucher.',
    'Pour une lampe : un triangle pour l’abat-jour, un rectangle étroit pour le pied et une ellipse pour le socle.',
    'Reproduis la lampe en trois formes simples. Ajoute ensuite son contour extérieur.',
    'Construis une chaussure avec trois grandes formes, puis affine sa silhouette.',
    'J’ai commencé par les grandes formes|Les éléments s’attachent entre eux|Les détails ne cachent pas la construction',
    'formes',
  ],
  [
    'Trouver les bonnes proportions',
    'Comparer les dimensions et les espaces.',
    'Choisis une unité de mesure : la largeur de l’objet, par exemple.|Compare sa hauteur à cette unité ; observe aussi les vides autour.|Place de petits repères avant de fermer les contours.',
    'Si une bouteille mesure trois fois sa largeur, construis un rectangle de rapport 1 pour 3 avant son col.',
    'Dessine la bouteille du modèle dans un cadre, puis compare largeur et hauteur.',
    'Dessine deux objets voisins : une tasse basse et une bouteille haute. Vérifie leur rapport de taille.',
    'J’ai choisi une unité|Les rapports hauteur-largeur sont cohérents|J’ai observé l’espace entre les objets',
    'proportions',
  ],
  [
    'Passer des formes aux volumes',
    'Construire des objets qui semblent avoir une profondeur.',
    'Un cercle est une forme plane ; une sphère représente un volume.|Les ellipses donnent une ouverture aux cylindres.|Les arêtes visibles d’un cube indiquent trois directions dans l’espace.',
    'Une tasse se construit avec deux ellipses reliées par ses côtés ; son anse s’ajoute au volume.',
    'Reproduis un cube et un cylindre. Dessine légèrement les parties cachées pour comprendre leur forme.',
    'Transforme un cylindre en tasse et deux blocs en petit meuble.',
    'Les ellipses s’alignent|Les faces restent cohérentes|L’objet possède une profondeur lisible',
    'volumes',
  ],
  [
    'Comprendre la perspective',
    'Construire une profondeur avec un point de fuite.',
    'La ligne d’horizon correspond au niveau des yeux.|Les lignes qui s’éloignent dans une même direction convergent vers le même point de fuite.|Les verticales restent verticales dans cet exercice frontal.',
    'Dans un couloir vu de face, les limites du plafond et du sol rejoignent le même point.',
    'Complète les quatre lignes du couloir vers le point violet.',
    'Dessine une pièce simple, puis ajoute une porte sur un mur latéral.',
    'Les lignes de profondeur convergent|J’ai conservé les verticales|Les éléments lointains paraissent plus petits',
    'perspective',
  ],
  [
    'Comprendre la lumière',
    'Distinguer lumière, ombre propre et ombre portée.',
    'Repère d’abord la direction de la lumière.|L’ombre propre appartient à l’objet ; l’ombre portée se projette sur le support.|Le volume se lit grâce à la transition entre zones claires et sombres.',
    'Avec une lumière en haut à gauche, la droite de la sphère s’assombrit et son ombre se projette vers la droite.',
    'Observe la sphère, puis hachure sa face opposée à la lumière.',
    'Dessine un cylindre éclairé d’en haut à droite. Place son ombre propre et son ombre au sol.',
    'Le côté éclairé reste clair|L’ombre suit le volume|L’ombre portée est cohérente',
    'lumiere',
  ],
  [
    'Utiliser les valeurs',
    'Créer du relief avec trois valeurs lisibles.',
    'La valeur désigne le degré de clarté, même sans couleur.|Commence avec trois groupes : clair, moyen et sombre.|Réserve le contraste le plus fort à la zone que tu veux faire regarder.',
    'Une sphère peut rester lisible avec un grand clair, un demi-ton et une petite zone sombre.',
    'Réalise trois cases de gris puis ombre le volume du modèle.',
    'Dessine un fruit avec seulement trois valeurs. Compare sa silhouette en plissant les yeux.',
    'Les trois valeurs se distinguent|Le clair reste préservé|Le contraste aide à lire le volume',
    'valeurs',
  ],
  [
    'Organiser une composition',
    'Choisir ce que le regard découvre en premier.',
    'Décide du sujet principal avant de remplir la feuille.|Les espaces vides participent à la composition.|Teste plusieurs miniatures avant de choisir un cadrage.',
    'Une tasse décalée laisse un espace pour son anse et son ombre ; centrée et coupée, elle produit un autre effet.',
    'Dessine trois cadres miniatures avec une tasse placée différemment.',
    'Compose une image avec une plante, un livre et une tasse. Choisis un élément principal.',
    'Le sujet principal est identifiable|Les marges sont intentionnelles|J’ai comparé plusieurs cadrages',
    'composition',
  ],
  [
    'Suggérer les matières',
    'Différencier bois, métal et tissu.',
    'Une texture se suggère avec quelques signes choisis.|Le bois présente des fibres ; le tissu des plis liés aux appuis.|Le métal se reconnaît souvent à des contrastes nets entre reflets clairs et sombres.',
    'Une petite zone de fibres suffit à évoquer une table en bois, sans remplir toute sa surface.',
    'Réalise trois cases : fibres, plis et reflets.',
    'Dessine un mug métallique posé sur un tissu, en réservant les détails à quelques zones.',
    'Les matières se distinguent|Les marques suivent la forme|J’ai gardé des zones calmes',
    'matieres',
  ],
  [
    'Construire une silhouette humaine',
    'Organiser une posture avant son contour.',
    'Trace une ligne d’action qui résume le mouvement.|Place tête, cage thoracique et bassin avant les membres.|Repère les appuis et compare les longueurs sur la référence.',
    'Une personne penchée possède une ligne d’action inclinée ; ses jambes organisent les appuis au sol.',
    'Reproduis la silhouette schématique et marque ses appuis.',
    'Dessine une silhouette qui atteint une étagère, puis une personne assise.',
    'Le geste est lisible|Les articulations se relient|Les appuis soutiennent la posture',
    'silhouette',
  ],
  [
    'Construire un visage',
    'Placer les grandes masses d’un visage de face.',
    'Construis d’abord un volume simple et son axe vertical.|Les yeux se situent souvent près du milieu de la hauteur tête entière ; ajuste à la référence.|Compare espacements et inclinaisons avant de dessiner cils ou cheveux.',
    'Les repères sont des points de départ, pas une formule qui rend tous les visages identiques.',
    'Place les axes, les yeux, le nez et la bouche sur le modèle simplifié.',
    'Dessine deux visages de face en modifiant leurs proportions sans perdre leur alignement.',
    'Les traits suivent les axes|Les espacements sont comparés|J’ai ajouté les détails après les masses',
    'visage',
  ],
  [
    'Terminer un dessin',
    'Passer d’une construction à une image cohérente.',
    'Vérifie d’abord la composition et les proportions.|Choisis une seule direction de lumière pour cette étude.|Renforce les détails utiles, puis allège les traits de construction.',
    'Un dessin terminé peut garder des zones esquissées : le niveau de détail sert ton intention.',
    'Construis la petite nature morte du modèle avec des traits légers.',
    'Finalise une scène avec une tasse, une bouteille et un livre. Conserve ton premier essai pour comparer.',
    'Proportions et perspective sont cohérentes|La lumière reste constante|Les détails servent le sujet',
    'scene',
  ],
])
export const WRITE_LESSONS = rows('ecriture', [
  [
    'Trouver les mots justes',
    'Remplacer les formulations vagues par des détails précis.',
    'Choisis un nom concret avant d’ajouter plusieurs adjectifs.|Un verbe précis peut remplacer une longue explication.|Sélectionne les détails qui servent la scène.',
    '« Un endroit agréable » devient « Une terrasse à l’ombre, deux chaises face au jardin ».',
    'Réécris : « Il alla rapidement dans un endroit très sombre. » Choisis un lieu et un verbe précis.',
    'Décris une gare presque vide avec trois détails concrets, sans utiliser « beau », « bizarre » ou « endroit ».',
    'Les noms sont précis|Les verbes portent l’action|Chaque détail apporte quelque chose',
    '',
  ],
  [
    'Montrer une émotion',
    'Faire ressentir une émotion à travers les gestes.',
    'Les gestes, perceptions et paroles peuvent suggérer une émotion.|Choisis des signes cohérents avec ton personnage et la situation.|Nommer directement une émotion reste utile lorsque le récit a besoin d’aller vite.',
    'Lina relut trois fois son prénom sur le badge. Quand la porte s’ouvrit, elle essuya ses paumes sur son pantalon.',
    'Transforme « Lina était stressée avant son entretien » en deux phrases observables.',
    'Une personne attend un message important. Écris une courte scène sans les mots « stress », « peur » et « inquiet ».',
    'L’émotion se comprend|Les détails servent la scène|Le point de vue reste cohérent',
    '',
  ],
  [
    'Donner du rythme',
    'Utiliser la longueur des phrases et les paragraphes.',
    'Les phrases longues peuvent installer une continuité ou une accumulation.|Une phrase courte peut marquer une rupture.|Le rythme naît aussi des répétitions, des sons et des paragraphes.',
    '« Il avançait, longeant les vitrines fermées. Un bruit. Il s’arrêta. » La rupture attire l’attention.',
    'Écris l’arrivée d’un train dans un rythme calme, puis urgent.',
    'Raconte une recherche de clés en cinq phrases. Fais sentir une accélération sans écrire « vite ».',
    'Les variations ont un effet|Les coupures sont choisies|La scène reste compréhensible',
    '',
  ],
  [
    'Choisir un point de vue',
    'Contrôler les informations accessibles au lecteur.',
    'Un narrateur à la première personne rapporte ce qu’il perçoit ou croit.|Un point de vue limité ne connaît pas directement les pensées des autres.|On peut changer de point de vue, mais il faut rendre le changement lisible.',
    '« Il détourna les yeux ; je crus qu’il mentait » distingue observation et interprétation.',
    'Raconte une porte qui se ferme depuis l’intérieur, puis depuis le couloir.',
    'Deux personnes se retrouvent après une dispute. Raconte depuis une seule conscience.',
    'Je sais qui perçoit|Les pensées d’autrui ne sont pas affirmées sans raison|Les informations sont cohérentes',
    '',
  ],
  [
    'Créer un personnage crédible',
    'Relier un désir, un obstacle et une contradiction.',
    'Un désir donne une direction au personnage.|Un obstacle oblige à choisir ou à agir.|Une contradiction devient intéressante lorsqu’elle produit un comportement.',
    'Une personne veut être reconnue mais refuse de montrer son travail : cette tension peut déclencher une scène.',
    'Donne à un personnage un désir, un obstacle et une décision coûteuse.',
    'Écris une scène où quelqu’un doit demander de l’aide alors qu’il veut paraître autonome.',
    'Le désir est identifiable|L’obstacle influence l’action|La décision révèle le personnage',
    '',
  ],
  [
    'Écrire un dialogue naturel',
    'Différencier les voix et laisser du sous-entendu.',
    'Une réplique répond à une intention, pas seulement à une question.|Évite de faire réciter ce que les personnages savent déjà.|Les gestes et les silences peuvent modifier le sens d’une phrase.',
    '« Tu pars ? — Mon sac est prêt. » La réponse peut exprimer une décision sans l’expliquer.',
    'Réécris « Comme tu le sais, nous sommes frères depuis toujours » dans un échange crédible.',
    'Deux colocataires discutent d’une tasse cassée, mais le désaccord concerne surtout leur confiance.',
    'Chaque voix a une intention|L’exposition reste discrète|Le sous-entendu se comprend',
    '',
  ],
  [
    'Installer une ambiance',
    'Choisir des sensations qui produisent un effet.',
    'Le décor se découvre depuis un regard particulier.|Deux ou trois sensations précises suffisent souvent.|Les détails choisis orientent l’ambiance sans multiplier les adjectifs.',
    'Un néon qui grésille et une chaise encore tiède ne suggèrent pas le même lieu qu’une fenêtre ouverte et une odeur de pain.',
    'Décris une cuisine accueillante, puis inquiétante, en conservant les mêmes meubles.',
    'Un personnage entre dans une bibliothèque après la fermeture. Choisis une ambiance et trois sensations.',
    'Les sensations convergent|Le décor reste concret|L’ambiance ne repose pas sur une étiquette',
    '',
  ],
  [
    'Créer de la tension',
    'Donner un enjeu et une évolution à la scène.',
    'Le lecteur comprend ce qui pourrait être gagné ou perdu.|Un obstacle transforme une intention simple en problème.|Une information retardée doit rester crédible, pas artificiellement cachée.',
    'Récupérer un dossier devient tendu si la porte se ferme dans deux minutes et que le bon dossier reste introuvable.',
    'Ajoute un enjeu et un obstacle à « Elle cherche un document ».',
    'Un personnage doit rendre un objet avant que son absence soit remarquée. Fais évoluer la difficulté.',
    'L’enjeu est clair|L’obstacle change la situation|La tension progresse',
    '',
  ],
  [
    'Donner une direction au récit',
    'Relier déclencheur, choix et conséquence.',
    'La situation de départ établit un équilibre.|Un déclencheur oblige à agir.|La conséquence doit découler des décisions prises.',
    'Recevoir une lettre pousse à rendre visite à quelqu’un ; cette visite révèle un secret qui change la relation.',
    'Construis un plan en quatre lignes : départ, déclencheur, choix, conséquence.',
    'Écris une histoire courte dans laquelle une erreur d’adresse provoque une rencontre inattendue.',
    'Les événements se relient|Le personnage agit|La conséquence vient de ses choix',
    '',
  ],
  [
    'Réussir son début',
    'Donner une raison de continuer à lire.',
    'Un début peut proposer une voix, une situation ou une question.|Le mystère fonctionne mieux si le lecteur possède quelques repères.|Évite les informations qui pourront apparaître naturellement plus tard.',
    '« Le colis portait mon nom, mais il avait été envoyé dix ans plus tôt. » Une anomalie crée une question précise.',
    'Écris deux ouvertures pour l’arrivée d’un colis : l’une par l’action, l’autre par la voix du narrateur.',
    'Rédige un début autour d’une place réservée à quelqu’un qui ne vient plus.',
    'Le lecteur trouve un point d’entrée|Une attente apparaît|Les informations restent utiles',
    '',
  ],
  [
    'Écrire une fin qui tient',
    'Conclure en cohérence avec les éléments préparés.',
    'Une fin peut résoudre l’action tout en laissant une émotion ouverte.|Une surprise gagne à être préparée par des indices discrets.|Une révélation sans lien avec le récit ressemble à une solution arbitraire.',
    'Si une clé a été évoquée au début, son usage final peut donner un sens nouveau à ce détail.',
    'Imagine deux fins pour une personne qui cherche à rendre une clé : une fermée, une ouverte.',
    'Écris une courte scène puis une fin qui réutilise un détail introduit dès la première phrase.',
    'La fin découle de la scène|Les éléments utiles sont préparés|L’effet final est intentionnel',
    '',
  ],
  [
    'Réviser sans perdre sa voix',
    'Relire en plusieurs passes avec un objectif.',
    'Relis d’abord la cohérence de la scène.|Cherche ensuite répétitions, formulations vagues et passages superflus.|Garde les particularités qui servent la voix du texte.',
    '« Il commença à se mettre à courir rapidement » peut devenir « Il s’élança ». Le choix dépend du rythme recherché.',
    'Allège : « Elle regarda avec ses yeux la porte qui était fermée et qui ne s’ouvrait pas. »',
    'Reprends un texte de ton carnet ou crée un paragraphe. Garde le premier jet et produis une version révisée.',
    'La scène est cohérente|Les coupes améliorent la lecture|Ma voix reste reconnaissable',
    '',
  ],
])
const pianoRows: Row[] = [
  [
    'Se repérer sur le clavier',
    'Retrouver les notes avec les touches noires.',
    'Les touches noires forment des groupes de deux et trois.|Do est la touche blanche juste avant un groupe de deux.|Les noms se répètent à chaque octave.',
    'Do, Ré, Mi précèdent Fa, Sol, La, Si.',
    'Joue Do, Ré et Mi avec les noms affichés.',
    'Masque les noms et retrouve Do, Mi, Sol, puis le Do suivant.',
    'Je repère le groupe de deux|Je retrouve Do sans étiquette|Je distingue deux octaves',
    '',
  ],
  [
    'Jouer régulièrement',
    'Garder une pulsation stable.',
    'La pulsation est un repère régulier.|Écoute plusieurs battements avant de commencer.|La régularité compte davantage que la vitesse.',
    'Quatre Do espacés de la même durée forment un premier exercice de pulsation.',
    'Active le métronome lent et joue un Do par battement.',
    'Joue quatre Sol réguliers, puis quatre Do, sans accélérer à la transition.',
    'Les départs sont réguliers|Je garde un tempo confortable|Je réécoute mon essai',
    '',
  ],
  [
    'Comprendre les durées',
    'Alterner notes longues, courtes et silences.',
    'Une note peut durer plusieurs pulsations.|Un silence occupe du temps même si rien ne sonne.|Relâcher la touche termine la tenue lorsque la pédale est désactivée.',
    'Do tenu deux temps, Ré un temps, Mi un temps : les durées organisent la phrase.',
    'Écoute puis reproduis le motif avec la pédale coupée.',
    'Rejoue le motif en respectant les tenues et une respiration finale.',
    'Les notes longues durent davantage|Je laisse une respiration|Je ne confonds pas vitesse et durée',
    '',
  ],
  [
    'Ma première mélodie',
    'Apprendre une phrase puis l’enchaîner.',
    'Écoute la phrase entière avant de jouer.|Repère les notes répétées et les petits déplacements.|Travaille une phrase à la fois avant de les réunir.',
    'Do Ré Mi Ré, puis Mi Fa Sol : une montée suivie d’un petit retour.',
    'Joue la première phrase avec le guide visuel.',
    'Masque le guide et joue les deux phrases du modèle.',
    'Je connais le départ|Les enchaînements sont fluides|Je peux réécouter et reprendre',
    '',
  ],
  [
    'Reconnaître les intervalles',
    'Entendre et retrouver la distance entre deux notes.',
    'Un intervalle relie deux hauteurs.|Do-Ré monte d’un degré, Do-Mi en franchit deux.|Compare des intervalles depuis la même note de départ.',
    'Écoute Do-Ré, puis Do-Sol : le second déplacement est plus large.',
    'Écoute les paires du modèle et retrouve-les sur le clavier.',
    'Joue une seconde, une tierce et une quinte à partir de Do.',
    'Je distingue petit et grand écart|Je retrouve la note de départ|Je compare en écoutant',
    '',
  ],
  [
    'Construire des accords',
    'Associer trois notes et entendre leur couleur.',
    'Une triade majeure empile une tierce majeure et une tierce mineure.|Do majeur contient Do, Mi, Sol ; Do mineur contient Do, Mi bémol, Sol.|Sur le clavier tactile, joue les trois notes ensemble ou successivement pour les explorer.',
    'Do–Mi–Sol puis Do–Mi♭–Sol : la note du milieu change la couleur.',
    'Joue Do, Mi, Sol lentement, puis ensemble si tes appuis le permettent.',
    'Compare Do majeur et Do mineur : Mi bémol correspond à Ré dièse sur ce clavier.',
    'Je retrouve les trois notes|J’entends le changement central|Je garde les mains détendues',
    '',
  ],
  [
    'Enchaîner des accords',
    'Passer entre des groupes de notes.',
    'Prépare le prochain accord avant de changer.|Une note commune peut servir de repère.|Commence lentement, en jouant les accords en arpèges si nécessaire.',
    'Do majeur : Do Mi Sol. Fa majeur : Fa La Do. Sol majeur : Sol Si Ré.',
    'Joue les trois notes de chaque accord dans l’ordre du modèle.',
    'Enchaîne Do majeur, Fa majeur, Sol majeur puis Do majeur.',
    'Je prépare la transition|Les groupes restent identifiables|Je privilégie la régularité',
    '',
  ],
  [
    'Donner une expression',
    'Changer l’effet d’une phrase.',
    'Une articulation liée rapproche les sons ; détachée, elle les sépare.|Un silence bref peut souligner une fin de phrase.|Le tactile ne mesure pas la force : travaille la tenue et les respirations.',
    'Le même Do Ré Mi Ré peut paraître lié ou détaché selon le moment où tu relâches.',
    'Joue le modèle avec des notes liées, puis détachées.',
    'Enregistre une version expressive en choisissant tes respirations.',
    'Les articulations sont choisies|La phrase possède une fin|J’écoute l’effet produit',
    '',
  ],
  [
    'Lire des repères musicaux',
    'Associer quelques positions sur la portée aux touches.',
    'La portée utilise cinq lignes ; les interlignes portent aussi des notes.|En clé de sol, la deuxième ligne depuis le bas porte Sol.|Commence avec Mi, Fa et Sol autour des deux premières lignes.',
    'Mi : première ligne ; Fa : premier interligne ; Sol : deuxième ligne.',
    'Observe les trois notes sur la portée, puis joue Mi Fa Sol.',
    'Masque les noms et joue les repères de la portée.',
    'Je compte depuis le bas|Je distingue ligne et interligne|Je retrouve la touche correspondante',
    'portee',
  ],
  [
    'Jouer des arpèges',
    'Déployer un accord note après note.',
    'Un arpège utilise successivement les notes d’un accord.|Garde le même ordre au début pour stabiliser le geste.|Le retour vers le grave peut former une boucle régulière.',
    'Do Mi Sol Mi revient vers la note de départ sans ajouter de nouvelle harmonie.',
    'Reproduis lentement le motif montant et descendant.',
    'Joue deux boucles, puis déplace le motif sur Fa La Do La.',
    'Les notes appartiennent au groupe|Le retour reste régulier|Je peux ralentir sans me perdre',
    '',
  ],
  [
    'Inventer une phrase musicale',
    'Composer avec peu de notes.',
    'Une contrainte réduit les possibilités et aide à commencer.|Répéter un motif donne un repère à l’oreille.|Une variation change une note ou un rythme sans tout remplacer.',
    'Avec Do Ré Mi Sol, invente quatre notes puis change seulement la dernière.',
    'Explore librement Do, Ré, Mi et Sol.',
    'Enregistre deux phrases : un motif, puis sa variation. Aucun modèle unique n’est attendu.',
    'Le motif se reconnaît|La variation est perceptible|J’ai réécouté ma création',
    '',
  ],
  [
    'Apprendre un petit morceau',
    'Assembler les phrases d’une étude originale.',
    'Repère les phrases semblables pour réduire le travail.|Isole une transition difficile au lieu de recommencer toujours au début.|Enregistre l’ensemble seulement lorsque les passages sont confortables.',
    'Cette étude originale combine montée, retour et deux accords déployés.',
    'Écoute puis travaille chaque phrase du modèle séparément.',
    'Joue l’étude entière ; écoute ton essai puis reprends un passage précis.',
    'Les phrases s’enchaînent|Les pauses sont choisies|Je sais quel passage retravailler',
    '',
  ],
]
const sequences = [
  'C4 D4 E4 G4 C5',
  'C4 C4 C4 C4 G4 G4 G4 G4',
  'C4 D4 E4 C4',
  'C4 D4 E4 D4 E4 F4 G4',
  'C4 D4 C4 E4 C4 G4',
  'C4 E4 G4 C4 D#4 G4',
  'C4 E4 G4 F4 A4 C5 G4 B4 D5 C4 E4 G4',
  'C4 D4 E4 D4 C4',
  'E4 F4 G4 G4 F4 E4',
  'C4 E4 G4 E4 F4 A4 C5 A4',
  'C4 D4 E4 G4',
  'C4 D4 E4 G4 E4 D4 C4 C4 E4 G4 F4 A4 C5 A4 G4 E4 D4 C4',
]
export const PIANO_LESSONS = rows('piano', pianoRows).map((l, i) => ({
  ...l,
  notes: sequences[i]!.split(' '),
  beats: i === 2 ? [2, 1, 1, 2] : sequences[i]!.split(' ').map(() => 1),
}))
