import type { Lesson } from './types.ts'
import type { StudioTask } from '../studio.ts'
function q(
  id: string,
  title: string,
  prompt: string,
  solution: string,
  explanation: string,
  alternatives: string[] = [],
): StudioTask {
  return {
    id,
    title,
    kind: 'input',
    prompt,
    solution,
    alternatives,
    evidence: [],
    explanation: explanation.split('|'),
    hints: [
      'Reformule la consigne avec tes propres mots.',
      'Note les informations certaines avant de tester une réponse.',
      explanation.split('|')[0]!,
    ],
  }
}
const french = [
  [
    'Trouver le sujet et le verbe',
    'Identifier le sujet, même lorsqu’il est éloigné du verbe.',
    'Pose la question « qui est-ce qui ? » devant le verbe.|Un groupe entre le sujet et le verbe ne change pas l’accord.|Le sujet peut venir après le verbe.',
    'Au fond du jardin poussent trois rosiers. Le sujet est « trois rosiers ».',
    'Les clés de la maison ___ sur la table. Complète avec être au présent.',
    'sont',
    'Le sujet est « les clés », pluriel ; « de la maison » le précise sans le remplacer.',
    'Dans la cour ___ les enfants. Complète avec jouer au présent.',
    'jouent',
    '« Les enfants » est le sujet placé après le verbe : troisième personne du pluriel.',
  ],
  [
    'Conjuguer au présent',
    'Revoir les formes fréquentes du présent.',
    'Les verbes du premier groupe suivent souvent -e, -es, -e, -ons, -ez, -ent.|Les verbes fréquents peuvent changer de radical : je peux, nous pouvons.|Vérifie le sujet avant de choisir la terminaison.',
    'Nous faisons ; vous faites. La forme ne se déduit pas toujours du seul infinitif.',
    'Tu ___ venir demain. Complète avec pouvoir au présent.',
    'peux',
    'Avec « tu », pouvoir donne « peux ».',
    'Vous ___ attention, puis nous ___ le travail. Complète avec faire et finir ; sépare par une virgule.',
    'faites, finissons',
    'Faire : vous faites. Finir, verbe du deuxième groupe : nous finissons.',
  ],
  [
    'Accorder dans le groupe nominal',
    'Accorder les mots qui dépendent du nom.',
    'Le déterminant annonce souvent le genre et le nombre.|L’adjectif s’accorde avec le nom qu’il qualifie.|Repère chaque groupe nominal avant de corriger.',
    'Des fenêtres ouvertes : les trois mots appartiennent au même groupe pluriel.',
    'Corrige uniquement l’adjectif : « des robes léger ».',
    'légères',
    '« Robes » est féminin pluriel : légères.',
    'Corrige les deux adjectifs : « ces vieux portes bleu ». Sépare-les par une virgule.',
    'vieilles, bleues',
    '« Portes » est féminin pluriel : vieilles et bleues s’y accordent.',
  ],
  [
    'Distinguer les homophones courants',
    'Choisir grâce à un test de remplacement.',
    'A peut se remplacer par avait ; à est une préposition.|Sont peut se remplacer par étaient ; son indique une possession.|Ont peut se remplacer par avaient ; on peut souvent se remplacer par il.',
    'Elle a un livre à rendre : « avait » fonctionne pour le premier a seulement.',
    'Complète : « Il ___ rendez-vous ___ midi. » Sépare les réponses par une virgule.',
    'a, à',
    'Il avait rendez-vous fonctionne ; le second mot introduit l’heure.',
    'Complète : « ___ dit que ses amis ___ déjà prévenu ___ frère. » Sépare par une virgule.',
    'on, ont, son',
    'On est sujet de dit ; les amis avaient prévenu ; son détermine frère.',
  ],
  [
    'Imparfait ou passé composé ?',
    'Choisir le temps selon le rôle de l’action.',
    'L’imparfait peut présenter une habitude ou une situation en cours.|Le passé composé présente ici un événement achevé qui fait avancer le récit.|Le contexte compte : la durée réelle ne suffit pas à choisir.',
    'Il pleuvait quand le téléphone a sonné : situation puis événement.',
    'Chaque été, nous ___ ici. Complète avec venir à l’imparfait.',
    'venions',
    '« Chaque été » présente une habitude passée : nous venions.',
    'Hier, je ___ quand Léa ___. Complète avec lire à l’imparfait puis arriver au passé composé ; sépare par une virgule.',
    'lisais, est arrivée',
    'La lecture est en cours : lisais. L’arrivée est l’événement : est arrivée, accord avec Léa.',
  ],
  [
    'Futur ou conditionnel ?',
    'Distinguer prévision, hypothèse et demande.',
    'Le futur présente ici une action envisagée comme à venir.|Le conditionnel peut exprimer une hypothèse ou une demande atténuée.|Dans l’hypothèse « si + imparfait », la conséquence est au conditionnel.',
    'Si j’avais le temps, je viendrais. On n’écrit pas « si j’aurais » dans cette construction.',
    'Demain, je ___ à huit heures. Complète avec partir au futur.',
    'partirai',
    'Première personne du futur : partirai. La terminaison est -ai.',
    'Si nous ___ plus de temps, nous ___ davantage. Complète avec avoir puis lire ; sépare par une virgule.',
    'avions, lirions',
    'Après si : imparfait, avions. Conséquence hypothétique : conditionnel, lirions.',
  ],
  [
    'Choisir entre -er, -é et -ez',
    'Identifier la forme avant sa terminaison.',
    'Remplace par prendre pour tester un infinitif.|Remplace par pris pour tester un participe passé.|Avec vous au présent d’un verbe en -er, la terminaison est généralement -ez.',
    'Vous allez préparer le repas que vous avez commandé.',
    'Il faut ___ la porte. Complète avec fermer.',
    'fermer',
    'Il faut prendre fonctionne : infinitif, fermer.',
    'Vous ___ le dossier que vous avez ___. Complète avec vérifier au présent puis préparer au participe ; sépare par une virgule.',
    'vérifiez, préparé',
    'Vous vérifiez : présent. Avez préparé : participe passé ; le COD dossier est représenté par que avant, mais reste masculin singulier.',
  ],
  [
    'Accorder le participe passé',
    'Repérer auxiliaire et complément direct.',
    'Avec être, le participe s’accorde généralement avec le sujet dans les cas simples.|Avec avoir, il s’accorde avec le COD si ce COD est placé avant.|Les verbes pronominaux demandent une analyse particulière : cette leçon commence par les autres cas.',
    'Les lettres que j’ai écrites : que reprend lettres, COD placé avant.',
    'Elles sont ___. Complète avec arriver au participe passé.',
    'arrivées',
    'Avec être, accord avec elles : féminin pluriel.',
    'Complète : « Les affiches que nous avons ___ sont les mêmes que celles que Léa a ___. » Utilise imprimer puis choisir ; sépare par une virgule.',
    'imprimées, choisies',
    'Dans les deux propositions, que reprend un COD féminin pluriel placé avant : affiches puis celles.',
  ],
  [
    'Maîtriser les accords plus difficiles',
    'Retrouver le véritable donneur d’accord.',
    'Le mot le plus proche du verbe n’est pas forcément son sujet.|Avec qui, retrouve le mot auquel le pronom renvoie.|Relis la phrase sans les groupes intercalés.',
    'C’est toi qui choisis : qui reprend toi, donc deuxième personne.',
    'C’est moi qui ___ raison. Complète avec avoir au présent.',
    'ai',
    'Qui reprend moi : j’ai, donc ai.',
    'Les pages du carnet que tu me prêtes ___ utiles, mais c’est toi qui les ___. Complète avec être puis choisir au présent ; sépare par une virgule.',
    'sont, choisis',
    'Le sujet du premier verbe est pages, pluriel. Qui reprend toi : tu choisis.',
  ],
  [
    'Comprendre les pronoms',
    'Identifier la fonction et le référent.',
    'Se accompagne un verbe pronominal ; ce peut déterminer un nom.|Ces désigne ; ses marque la possession.|Leur devant un verbe est un pronom invariable ; devant un nom, leur ou leurs s’accorde en nombre avec ce nom.',
    'Elle leur prête leurs cahiers : premier leur pronom ; second leurs déterminant du pluriel cahiers.',
    'Elle ___ souvient de ___ jour. Complète par ce ou se ; sépare par une virgule.',
    'se, ce',
    'Se accompagne se souvenir ; ce détermine jour.',
    'Je ___ rends ___ livres. Complète avec leur ou leurs ; sépare par une virgule.',
    'leur, leurs',
    'Je leur rends : pronom sans s. Leurs livres : déterminant pluriel.',
  ],
  [
    'Construire et ponctuer une phrase',
    'Relier clairement les idées.',
    'Une virgule ne sépare normalement pas le sujet de son verbe.|Les deux-points peuvent annoncer une explication ou une liste.|Une incise peut être encadrée de deux virgules.',
    'Léa, malgré la fatigue, poursuit son travail : les virgules encadrent le groupe ajouté.',
    'Réécris en retirant la virgule incorrecte : « Les élèves de cette classe, préparent une exposition. »',
    'Les élèves de cette classe préparent une exposition.',
    'Le groupe entier « Les élèves de cette classe » est sujet de préparent.',
    'Ajoute uniquement deux virgules : « Nora malgré le bruit termine son texte. »',
    'Nora, malgré le bruit, termine son texte.',
    'Le groupe « malgré le bruit » est encadré ; le lien Nora-termine reste lisible.',
  ],
  [
    'Relire un texte avec méthode',
    'Corriger en plusieurs passes ciblées.',
    'Vérifie d’abord sujets et verbes.|Relis ensuite les accords dans les groupes nominaux.|Termine par les homophones et la ponctuation ; une relecture à voix haute peut aider.',
    'Séparer les vérifications évite de chercher toutes les erreurs en même temps.',
    'Corrige : « Les document sont prêt. »',
    'Les documents sont prêts.',
    'Les annonce le pluriel : documents. L’attribut prêts s’accorde avec documents.',
    'Corrige : « Si j’aurais le temps, je relirai les lettre que tu a envoyé. »',
    'Si j’avais le temps, je relirais les lettres que tu as envoyées.',
    'Si + imparfait : avais ; conséquence au conditionnel : relirais.|Lettres est pluriel ; tu as prend s ; que reprend lettres, COD avant avoir : envoyées.',
  ],
]
export const FRENCH_LEARNING: Lesson[] = french.map((r, i) => ({
  id: `learn-v1-francais-${i + 1}`,
  revision: 1,
  passion: 'francais',
  number: i + 1,
  level: Math.floor(i / 4),
  title: r[0]!,
  goal: r[1]!,
  teaching: r[2]!.split('|'),
  example: r[3]!,
  guided: 'Applique la méthode à la première phrase. La correction explique chaque choix.',
  practice: 'Passe au second exercice sans consulter la démonstration, puis vérifie ton raisonnement.',
  checklist: ['J’ai identifié la règle', 'Je sais expliquer ma correction', 'Je sais ce que je dois revoir'],
  tasks: [
    q(`fl-${i}-guided`, 'Essai guidé', r[4]!, r[5]!, r[6]!),
    q(`fl-${i}-practice`, 'À toi de vérifier', r[7]!, r[8]!, r[9]!),
  ],
}))
const logic = [
  [
    'Faits et suppositions',
    'Distinguer ce qui est certain de ce qui reste possible.',
    'Une information possible n’est pas une preuve.|Traduis chaque phrase sans lui ajouter de détail.|Un seul contre-exemple suffit à réfuter une conclusion prétendue certaine.',
    'Tous les dossiers rouges sont signés ne signifie pas que tous les dossiers signés sont rouges.',
    'Tous les badges bleus ouvrent A. Certains badges ouvrent A et B. Peut-on affirmer qu’un badge bleu ouvre B ? Réponds certain, impossible ou indéterminé.',
    'indéterminé',
    'Les badges ouvrant A et B pourraient tous être d’une autre couleur. Ils pourraient aussi être bleus : les deux situations respectent les faits.',
    'Tous les dossiers urgents sont relus. Aucun dossier relu n’est anonyme. Un dossier est anonyme. Peut-il être urgent ? Réponds oui ou non.',
    'non',
    'Urgent implique relu ; relu implique non anonyme. Un dossier anonyme ne peut donc pas être urgent.',
  ],
  [
    'Organiser les contraintes',
    'Construire un tableau d’attribution.',
    'Note les personnes en lignes et les objets en colonnes.|Une attribution certaine exclut les autres possibilités de la ligne et de la colonne.|Répète les exclusions jusqu’à stabiliser le tableau.',
    'Avec une seule attribution par personne, un objet déjà attribué ne peut pas servir à quelqu’un d’autre.',
    'Ari, Nora et Sam ont chacun une couleur différente : bleu, rouge, vert. Ari n’a ni rouge ni vert. Nora n’a pas rouge. Donne les couleurs dans l’ordre Ari, Nora, Sam, séparées par des virgules.',
    'bleu, vert, rouge',
    'Ari ne peut avoir que bleu. Nora ne peut alors avoir que vert. Il reste rouge à Sam.',
    'Quatre dossiers A, B, C, D vont à quatre salles 1, 2, 3, 4. A est dans une salle paire. B est juste avant A. C est après A. D n’est pas en 3. Donne les salles de A, B, C, D, séparées par des virgules.',
    '2, 1, 3, 4',
    'A ne peut être en 4 car C doit être après. Donc A=2, B=1. D ne peut être en 3, donc D=4 et C=3.',
  ],
  [
    'Croiser plusieurs indices',
    'Enchaîner des déductions partielles.',
    'Commence par l’indice qui réduit le plus les possibilités.|Conserve les liens entre les informations.|Vérifie toutes les contraintes sur la solution finale.',
    '« Juste avant » impose deux positions consécutives ; « avant » ne l’impose pas.',
    'Les réunions A, B, C occupent 9 h, 10 h, 11 h. B n’est pas à 9 h. A est après B. À quelle heure commence C ? Écris HH:MM.',
    '09:00',
    'B ne peut être à 11 h puisque A vient après. B=10 h, A=11 h, donc C=9 h.',
    'Cinq exposés A, B, C, D, E ont des places de 1 à 5. A est juste avant C. D est avant A. E est après C. B n’est ni premier ni dernier. C n’est pas quatrième. Donne l’ordre des lettres, sans espace.',
    'DACBE',
    'C ne peut être 2 car D précède A, ni 4 par l’indice, ni 5 car E vient après. Donc C=3 et A=2 ; D=1. B ne peut être dernier, donc B=4 et E=5.',
  ],
  [
    'Tester une hypothèse',
    'Suivre une possibilité jusqu’à la contradiction.',
    'Une hypothèse est provisoire : distingue-la des faits.|Déduis ses conséquences sans changer les règles en route.|Une contradiction élimine l’hypothèse, pas l’ensemble du problème.',
    'Si choisir A force à choisir B alors qu’A et B sont incompatibles, A doit être écarté.',
    'Choisir A impose B. A et B ne peuvent pas être choisis ensemble. Peut-on choisir A ? Oui ou non.',
    'non',
    'Supposer A impose B ; cela viole l’incompatibilité. A est impossible.',
    'Exactement deux options parmi A, B, C, D sont retenues. A impose B ; B exclut D ; C impose D ; A et C sont incompatibles. D est retenue. Donne l’autre option.',
    'C',
    'D élimine B ; A imposerait B, donc A est aussi éliminée. Pour obtenir deux options, C est nécessaire et compatible avec D.',
  ],
  [
    'Raisonner avec les horaires',
    'Calculer des intervalles plutôt qu’une heure supposée.',
    'Une durée minimale donne une borne d’arrivée au plus tôt.|Une heure de sortie moins un trajet donne une borne de départ au plus tard.|L’intersection des intervalles décrit ce qui reste possible.',
    'Arrivée au plus tôt à 14 h 12 et départ au plus tard à 14 h 18 : six minutes disponibles, hors autres contraintes.',
    'Départ à 09:12, trajet de 8 min, retour au point de départ à 09:35 par un trajet de 10 min. Combien de minutes au maximum peut durer la visite ?',
    '5',
    'Arrivée au plus tôt à 09:20 ; départ au plus tard à 09:25 ; la visite dure au maximum 5 minutes.',
    'Une navette part à 10:00. Il faut 9 min pour aller du bureau à l’arrêt et arriver 3 min avant. Un entretien dure 12 min ; il ne peut commencer avant 10:22 sur une horloge de bureau qui avance de 50 min. Quelle est l’heure réelle limite de début de l’entretien ? Écris HH:MM.',
    '09:36',
    'Départ du bureau au plus tard à 09:48 pour être à l’arrêt à 09:57.|L’entretien doit donc commencer au plus tard à 09:36. Son début autorisé est 09:32 réel (10:22 moins 50 min), ce qui laisse un début possible entre 09:32 et 09:36.',
  ],
  [
    'Comprendre les conditions logiques',
    'Distinguer implication et réciproque.',
    'Si A alors B interdit uniquement A vrai et B faux.|B vrai ne suffit pas à conclure A vrai.|« Exactement un » exclut à la fois zéro et plusieurs cas vrais.',
    'Si une alarme sonne, une porte est ouverte. Une porte ouverte ne prouve pas que l’alarme sonne.',
    'Si A est vrai, B est vrai. B est faux. A est-il vrai ou faux ?',
    'faux',
    'A vrai imposerait B vrai. B faux exclut A vrai : c’est le raisonnement par contraposée.',
    'A implique B. B implique C. Exactement une des propositions A, B, C est vraie. Laquelle ?',
    'C',
    'Si A était vraie, les trois le seraient. Si B était vraie, B et C le seraient. Seule C peut être vraie.',
  ],
  [
    'Exploiter les nombres',
    'Combiner ordre, parité et sommes.',
    'La parité peut éliminer une famille entière de possibilités.|Une somme ne détermine pas toujours les chiffres : croise-la avec l’ordre.|Vérifie aussi les contraintes sur les chiffres distincts.',
    'Un nombre pair se termine par 0, 2, 4, 6 ou 8 ; cela ne dit rien de la parité de son premier chiffre.',
    'Un code a deux chiffres distincts de 1 à 5. Leur somme vaut 7. Le premier est impair et supérieur au second. Quel est ce code ?',
    '52',
    'Les paires de somme 7 sont 2 et 5, 3 et 4. Premier impair et supérieur donne seulement 5 puis 2.',
    'Un code a trois chiffres distincts de 1 à 8. Leur somme vaut 14. Le premier vaut le double du dernier. Le chiffre central est pair et plus petit que le dernier. Quel est ce code ?',
    '824',
    'Si le dernier vaut z, le premier vaut 2z et le centre vaut 14−3z. Les bornes donnent z entre 1 et 4.|z=1, 2 ou 3 donne un centre trop grand ou non conforme. z=4 donne 8, 2, 4, distincts et conformes.',
  ],
  [
    'Choisir un réseau ou un trajet',
    'Comparer des chemins complets sous contraintes.',
    'Additionne tous les coûts, y compris les passages obligatoires.|Un chemin localement court peut conduire à une solution globale plus longue.|Écarte les trajets qui ne respectent pas les contraintes avant de comparer leurs coûts.',
    'Comparer seulement la première liaison ne suffit pas : il faut atteindre l’objectif.',
    'Routes non orientées : S-A=3, A-T=5, S-B=5, B-T=2. Quel est le trajet le moins coûteux ? Écris SAT ou SBT.',
    'SBT',
    'SAT coûte 8 ; SBT coûte 7.',
    'Routes non orientées : S-A=2, S-B=5, A-C=4, B-C=1, C-T=3, A-T=9, B-T=5. Il faut passer par C et ne visiter aucun point deux fois. Quel est le coût minimal de S à T ?',
    '9',
    'S-A-C-T coûte 2+4+3=9 ; S-B-C-T coûte aussi 5+1+3=9.|Il existe deux trajets optimaux, mais le coût minimal demandé est unique.',
  ],
  [
    'Choisir sa méthode',
    'Associer le problème à une représentation utile.',
    'Les attributions se lisent dans un tableau.|Les horaires gagnent à être placés sur une frise.|Les dépendances et les trajets se représentent par un graphe.',
    'Le choix de la représentation peut éviter de garder toutes les informations en mémoire.',
    'Quatre personnes reçoivent chacune un métier et une ville distincts. Quel outil est le plus adapté : tableau, frise ou graphe ?',
    'tableau',
    'Le tableau permet de croiser les catégories et de marquer les exclusions.',
    'Une tâche B attend A. C attend A. D attend B et C. Durées : A=3, B=7, C=4, D=2. B et C peuvent être réalisées en parallèle. En combien de minutes le projet peut-il finir au plus tôt ?',
    '12',
    'A prend 3 min. B et C commencent ensemble ; la plus longue, B, prend 7 min. D ajoute 2 min : 3+7+2=12.',
  ],
  [
    'Trouver l’information manquante',
    'Reconnaître un problème qui a plusieurs solutions.',
    'Ne choisis pas arbitrairement entre deux solutions valides.|Cherche quelle information les distinguerait.|Un indice utile doit réduire l’ensemble des solutions possibles.',
    'Deux solutions restantes signifient parfois un indice manquant, pas une erreur de raisonnement.',
    'Ari et Nora ont rouge et bleu, chacun une couleur. Sans autre indice, combien d’attributions sont possibles ?',
    '2',
    'Ari rouge/Nora bleu ou Ari bleu/Nora rouge : les deux respectent les données.',
    'Un code est parmi 124, 142, 214, 241. Les deux questions possibles sont Q1 : le premier chiffre est-il 1 ? Q2 : le chiffre central est-il 4 ? Quelle question garantit une seule solution après une réponse, Q1, Q2 ou aucune ?',
    'aucune',
    'Q1 partage en deux groupes de deux ; Q2 aussi : 142/241 contre 124/214. Aucune ne suffit seule.',
  ],
  [
    'Vérifier un raisonnement',
    'Trouver un contre-exemple à une conclusion abusive.',
    'Une conclusion doit être vraie dans tous les cas autorisés.|Un contre-exemple respecte les prémisses mais contredit la conclusion.|Ne confonds pas plusieurs exemples favorables avec une preuve générale.',
    'Deux nombres impairs peuvent donner une somme paire : 3+5=8 suffit à réfuter « somme toujours impaire ».',
    '« Tous les nombres divisibles par 4 sont divisibles par 8. » Donne le plus petit entier strictement positif qui réfute cette phrase.',
    '4',
    '4 est divisible par 4 mais pas par 8 ; il respecte la prémisse et contredit la conclusion.',
    '« Si le produit de deux entiers positifs est pair, les deux entiers sont pairs. » Donne une paire de somme minimale qui réfute cela, dans l’ordre croissant, séparée par une virgule.',
    '1, 2',
    '1×2=2, pair, mais 1 est impair. La somme vaut 3 ; une somme plus petite impose 1 et 1, dont le produit est impair.',
  ],
  [
    'Résoudre un problème complet',
    'Combiner tableau, bornes et vérification.',
    'Sépare les contraintes de position des contraintes de durée.|Fixe les éléments forcés puis calcule les horaires.|Vérifie chaque indice indépendamment sur ta solution.',
    'Une solution est convaincante lorsqu’on peut expliquer chaque attribution et contrôler toutes les limites.',
    'A, B, C sont traités sans pause dès 09:00. B dure 15 min et doit finir à 09:35. A dure 20 min et C 10 min. Quel dossier précède B ?',
    'A',
    'B commence à 09:20. Seul A occupe les 20 minutes précédentes sans pause.',
    'Quatre opérations A, B, C, D sont faites sans pause dès 08:00, chacune une fois. Durées : A=12, B=8, C=15, D=5 min. C est juste après A ; D est après C ; B finit avant 08:10. À quelle heure commence D ? Écris HH:MM.',
    '08:35',
    'B doit être premier : il finit à 08:08. A puis C suivent, car D doit venir après C.|A finit à 08:20 ; C à 08:35 ; D commence donc à 08:35.',
  ],
]
export const LOGIC_LEARNING: Lesson[] = logic.map((r, i) => ({
  id: `learn-v1-logique-${i + 1}`,
  revision: 1,
  passion: 'logique',
  number: i + 1,
  level: Math.floor(i / 4),
  title: r[0]!,
  goal: r[1]!,
  teaching: r[2]!.split('|'),
  example: r[3]!,
  guided: 'Commence par la méthode expliquée. Note tes déductions avant de vérifier.',
  practice: 'Résous le second problème. Tu peux demander un indice ou terminer pour lire le raisonnement.',
  checklist: [
    'Je distingue les faits et les hypothèses',
    'J’ai vérifié chaque contrainte',
    'Je peux expliquer ma conclusion',
  ],
  tasks: [
    q(`ll-${i}-guided`, 'Raisonnement guidé', r[4]!, r[5]!, r[6]!),
    q(`ll-${i}-practice`, 'Problème autonome', r[7]!, r[8]!, r[9]!),
  ],
}))
