import { SPORT_EXERCISES, type SportExerciseId } from '../sport.ts'
import type { Lesson } from './types.ts'
const data: [string, string, SportExerciseId, string, string, string][] = [
  [
    'Comprendre sa posture',
    'Observer ses appuis avant de commencer.',
    'march',
    'Une posture se règle selon le mouvement ; il n’existe pas une position figée pour tout faire.|Commence debout avec un espace dégagé.|Observe les appuis, puis bouge lentement sans bloquer ta respiration.',
    'Marche doucement sur place et repère le transfert de poids d’un pied à l’autre.',
    'Écris deux repères qui t’aident à rester stable, puis essaie de nouveau.',
  ],
  [
    'Apprendre le squat',
    'Contrôler la descente et la remontée.',
    'squat',
    'Commence avec une petite amplitude confortable.|Observe le déplacement des hanches et des genoux.|La profondeur augmente seulement si tu conserves tes appuis et ton contrôle.',
    'Essaie trois petites descentes en observant les talons.',
    'Compare deux amplitudes confortables et note celle que tu maîtrises le mieux.',
  ],
  [
    'Apprendre les pompes',
    'Choisir un appui adapté pour pousser.',
    'wall',
    'Le mur permet de découvrir le geste avec une charge réduite.|Rapprocher les pieds du mur rend cette variante plus accessible.|La progression vers le sol dépend de la maîtrise du placement, pas d’un calendrier.',
    'Essaie trois pompes au mur, lentement.',
    'Teste deux distances confortables au mur et choisis celle qui permet de garder le corps aligné.',
  ],
  [
    'Comprendre le gainage',
    'Stabiliser le tronc tout en respirant.',
    'plank',
    'Un maintien court et maîtrisé est utile pour apprendre.|Respirer fait partie de l’exercice.|Repose-toi dès que tu perds le placement ; le temps n’est pas une obligation.',
    'Observe les appuis et essaie un maintien de quelques secondes.',
    'Répète un court essai après une pause et note le repère qui t’aide à garder ton bassin stable.',
  ],
  [
    'Maîtriser les fentes',
    'Organiser les appuis et l’équilibre.',
    'lunge',
    'Garde un écart latéral entre les pieds pour une base stable.|Commence par une descente de faible amplitude.|Travaille les deux côtés en respectant leur confort propre.',
    'Place un pied en arrière et essaie une petite descente de chaque côté.',
    'Note la position des pieds qui te permet de rester stable, puis répète lentement.',
  ],
  [
    'Comprendre le pont fessier',
    'Soulever le bassin avec contrôle.',
    'bridge',
    'Le mouvement vient des hanches, sans chercher à cambrer davantage.|La hauteur reste secondaire par rapport au contrôle.|La tête et les épaules reposent sur le support.',
    'Observe la position de départ et essaie trois montées lentes.',
    'Compare une petite montée et une montée un peu plus ample, sans dépasser ton confort.',
  ],
  [
    'Coordonner ses mouvements',
    'Bouger les membres sans perdre la stabilité.',
    'bird',
    'Commence par un seul membre avant d’en coordonner deux.|Le bras et la jambe opposée peuvent ensuite se déplacer ensemble.|Réduis l’amplitude si le bassin tourne.',
    'Bouge un bras, puis une jambe, en revenant à la position de départ.',
    'Essaie le bras et la jambe opposée puis change de côté. Note ce qui aide à garder le bassin stable.',
  ],
  [
    'Respirer pendant l’effort',
    'Conserver une respiration régulière.',
    'wall',
    'Commence par observer ta respiration sans la forcer.|Pour cet essai de pompe au mur, souffle pendant la poussée et inspire au retour.|Ralentis si tu retiens involontairement ta respiration.',
    'Fais trois répétitions lentes en associant mouvement et respiration.',
    'Recommence à ton rythme ; note si tu arrives à respirer sans crispation.',
  ],
  [
    'Jouer sur le tempo',
    'Comparer deux vitesses contrôlées.',
    'squat',
    'Un tempo décrit le temps consacré aux phases d’un mouvement.|Ralentir aide à observer, mais augmente aussi le temps sous effort.|Adapte le nombre de répétitions et prends une pause si nécessaire.',
    'Essaie une descente lente sur trois temps et une remontée confortable.',
    'Compare avec ton rythme habituel, sans chercher une vitesse maximale. Note les différences de contrôle.',
  ],
  [
    'Choisir sa variante',
    'Adapter la difficulté à sa maîtrise actuelle.',
    'push',
    'Une variante est adaptée si tu peux contrôler le geste et respirer.|Choisir plus simple est une manière de travailler efficacement.|Modifie un paramètre à la fois : appui, amplitude ou durée.',
    'Compare la démonstration des pompes au mur et celle sur les genoux.',
    'Choisis la variante qui te convient aujourd’hui et explique ton choix dans le carnet.',
  ],
  [
    'Comprendre les pauses',
    'Reprendre lorsque le mouvement redevient maîtrisable.',
    'march',
    'La récupération permet de retrouver une respiration confortable et du contrôle.|Un chronomètre est un repère ; tu peux prolonger la pause.|Une douleur, un malaise ou une gêne inhabituelle demande d’arrêter, pas d’attendre la sonnerie pour continuer.',
    'Après un essai bref, lance une pause et observe comment tu te sens.',
    'Note les signes qui te permettent de reprendre confortablement ou de décider d’arrêter.',
  ],
  [
    'Construire une séance équilibrée',
    'Organiser plusieurs mouvements complémentaires.',
    'squat',
    'Choisis des mouvements qui sollicitent des fonctions différentes.|Prévois les transitions, les pauses et les variantes accessibles.|Pour cette leçon, prépare une séance sur papier dans le carnet : tu n’as pas à la réaliser entièrement.',
    'Associe une flexion de jambes, une poussée et un travail de stabilité.',
    'Écris une séance courte avec ordre, variantes et pauses. Justifie la complémentarité des mouvements.',
  ],
]
export const SPORT_LEARNING: Lesson[] = data.map((r, i) => ({
  id: `learn-v1-sport-${i + 1}`,
  revision: 1,
  passion: 'sport',
  number: i + 1,
  level: Math.floor(i / 4),
  title: r[0],
  goal: r[1],
  teaching: r[3].split('|'),
  example: SPORT_EXERCISES[r[2]].cue,
  guided: r[4],
  practice: r[5],
  exercise: r[2],
  checklist: ['Mes appuis sont stables', 'Je garde une amplitude confortable', 'Je respire et je peux faire une pause'],
  tasks: [],
}))
