/** Le catalogue et les prix sont partagés ; le serveur décide des achats. */
export const SHOP_CATEGORIES = ['ambiance', 'piano', 'theme', 'mascot', 'cover', 'profile', 'palette'] as const
export type ShopCategory = typeof SHOP_CATEGORIES[number]
export const SHOP_CATEGORY_LABELS: Record<ShopCategory, string> = { ambiance: 'Ambiances', piano: 'Piano', theme: 'Thèmes', mascot: 'Minuton', cover: 'Couvertures', profile: 'Profil', palette: 'Palettes' }
export interface ShopItem {
  id: string
  category: ShopCategory
  title: string
  description: string
  price: number
  symbol: string
  colors: readonly string[]
  /** Disponibilité à la vente. Les tenues retirées restent équipables par leurs propriétaires. */
  available: boolean
  /** Tenue privée offerte par code, jamais proposée à la vente. */
  redemptionOnly?: boolean
  difficulty?: string
  audio?: string
  composer?: string
  edition?: string
  mascotGroup?: 'sports' | 'arts' | 'olympus' | 'adventure' | 'halloween'
  mascotGender?: 'female'
  mascotArt?: { src: string; width: number; height: number; viewBox: [number, number, number, number] }
}
export const SHOP_ITEMS: readonly ShopItem[] = [
  { id: 'mascot-bruno-mars', category: 'mascot', title: 'Minuton Bruno Mars', description: 'Costume bleu nuit, lunettes dorées et micro : une tenue rétro en vedette dans la version de développement.', price: 0, symbol: '🎤', colors: ['#263B72', '#FFD16A'], available: true, mascotGroup: 'arts', mascotArt: { src: '/art/minuton-bruno-mars.webp', width: 1254, height: 1254, viewBox: [0, 0, 1254, 1254] } },
  { id: 'mascot-private-maradona', category: 'mascot', title: 'Minuton Maradona', description: 'Le numéro 10 argentin, sa chevelure bouclée et son ballon. Une tenue offerte en édition privée.', price: 0, symbol: '⚽', colors: ['#B7DFF5', '#F6ECD5'], available: false, redemptionOnly: true, mascotArt: { src: '/art/minuton-private-maradona.webp', width: 1254, height: 1254, viewBox: [0, 0, 1254, 1254] } },
  { id: 'mascot-private-poney', category: 'mascot', title: 'Minuton complice', description: 'Une robe ivoire, une tresse et un poney alezan. Une tenue offerte en édition privée.', price: 0, symbol: '🐴', colors: ['#F5E7D2', '#D7AC83'], available: false, redemptionOnly: true, mascotGender: 'female', mascotArt: { src: '/art/minuton-private-poney.webp', width: 1254, height: 1254, viewBox: [0, 0, 1254, 1254] } },
  { id: 'ambiance-aube', category: 'ambiance', title: 'Aube tranquille', description: 'Une composition originale aux notes douces, pour créer au calme.', price: 40, symbol: '🌅', colors: ['#FFC78A','#FFE6BA'], available: true, audio: '/music/shop-aube.mp3' },
  { id: 'ambiance-orbite', category: 'ambiance', title: 'Orbite', description: 'Une composition originale aux nappes spatiales et légères.', price: 60, symbol: '🪐', colors: ['#C1B3FF','#8CB8FF'], available: true, audio: '/music/shop-orbite.mp3' },
  { id: 'piano-lanterne', category: 'piano', title: 'La lanterne', description: 'Une petite mélodie originale à jouer note après note sur le clavier.', price: 50, symbol: '🎹', colors: ['#FFE6A7','#FFCC80'], available: true, difficulty: 'Débutant', audio: '/music/shop-lanterne.mp3' },
  { id: 'piano-constellation', category: 'piano', title: 'Constellation', description: 'Une mélodie originale en plusieurs phrases, pour travailler les déplacements.', price: 90, symbol: '✨', colors: ['#B6CDFF','#D8C8FF'], available: true, difficulty: 'Intermédiaire', audio: '/music/shop-constellation.mp3' },
  { id: 'piano-elise', category: 'piano', title: 'Lettre à Élise', composer: 'Beethoven', edition: 'Extrait guidé · adaptation à une main', description: 'Beethoven · un thème célèbre du domaine public, adapté note après note pour le clavier Scroll-up.', price: 160, symbol: '🌹', colors: ['#B6CDFF','#FFE6A7'], available: true, difficulty: 'Intermédiaire', audio: '/music/shop-elise.mp3' },
  { id: 'piano-joie', category: 'piano', title: 'Ode à la joie', composer: 'Beethoven', edition: 'Extrait guidé · adaptation à une main', description: 'Beethoven · un thème célèbre du domaine public, adapté note après note pour le clavier Scroll-up.', price: 100, symbol: '☀️', colors: ['#B6CDFF','#FFE6A7'], available: true, difficulty: 'Débutant', audio: '/music/shop-joie.mp3' },
  { id: 'piano-moonlight', category: 'piano', title: 'Sonate au clair de lune', composer: 'Beethoven', edition: 'Extrait guidé · adaptation à une main', description: 'Beethoven · un thème célèbre du domaine public, adapté note après note pour le clavier Scroll-up.', price: 180, symbol: '🌙', colors: ['#B6CDFF','#FFE6A7'], available: true, difficulty: 'Intermédiaire', audio: '/music/shop-moonlight.mp3' },
  { id: 'piano-canon', category: 'piano', title: 'Canon de Pachelbel', composer: 'Pachelbel', edition: 'Extrait guidé · adaptation à une main', description: 'Pachelbel · un thème célèbre du domaine public, adapté note après note pour le clavier Scroll-up.', price: 140, symbol: '🎼', colors: ['#B6CDFF','#FFE6A7'], available: true, difficulty: 'Débutant', audio: '/music/shop-canon.mp3' },
  { id: 'piano-bach-prelude', category: 'piano', title: 'Prélude en do majeur', composer: 'Bach', edition: 'Extrait guidé · adaptation à une main', description: 'Bach · un thème célèbre du domaine public, adapté note après note pour le clavier Scroll-up.', price: 160, symbol: '🎹', colors: ['#B6CDFF','#FFE6A7'], available: true, difficulty: 'Intermédiaire', audio: '/music/shop-bach-prelude.mp3' },
  { id: 'piano-gymnopedie', category: 'piano', title: 'Gymnopédie nº 1', composer: 'Satie', edition: 'Extrait guidé · adaptation à une main', description: 'Satie · un thème célèbre du domaine public, adapté note après note pour le clavier Scroll-up.', price: 140, symbol: '☁️', colors: ['#B6CDFF','#FFE6A7'], available: true, difficulty: 'Débutant', audio: '/music/shop-gymnopedie.mp3' },
  { id: 'piano-davy-jones', category: 'piano', title: 'Davy Jones', description: 'Retrouve la partition officielle de Hans Zimmer et entraîne-toi sur le clavier libre. Les notes guidées ne sont pas encore disponibles.', price: 0, symbol: '🏴‍☠️', colors: ['#BDD6D5','#D3E3DE'], available: false, difficulty: 'Clavier libre · partition externe' },
  { id: 'theme-crepuscule', category: 'theme', title: 'Crépuscule', description: 'Une palette pêche et prune qui habille toute l’application.', price: 120, symbol: '🌇', colors: ['#FFF0E6','#E68778','#A390CA'], available: true },
  { id: 'theme-jardin', category: 'theme', title: 'Jardin', description: 'Un fond crème et des accents verts pour une ambiance végétale.', price: 120, symbol: '🌿', colors: ['#EDF5E8','#77C5A1','#DCEAA7'], available: true },
  { id: 'mascot-beret', category: 'mascot', title: 'Minuton artiste', description: 'Un béret pour Minuton, visible sur l’accueil et dans ton profil.', price: 40, symbol: '🎨', colors: ['#FFA995','#FFE1A6'], available: true, mascotGroup: 'arts' },
  { id: 'mascot-pianiste', category: 'mascot', title: 'Minuton pianiste', description: 'Un nœud papillon et un petit clavier pour accompagner tes mélodies. Une tenue visible sur ta mascotte après activation.', price: 70, symbol: '🎹', colors: ['#95C9E8', '#B7A2EF'], available: true, mascotGroup: 'arts' },
  { id: 'mascot-casque', category: 'mascot', title: 'Minuton mélomane', description: 'Un casque pour accompagner tes moments créatifs.', price: 60, symbol: '🎧', colors: ['#B2CFFF','#D6BEF5'], available: false },
  { id: 'cover-carnet', category: 'cover', title: 'Carnet d’artiste', description: 'Des rayures colorées pour les couvertures de tes projets sans photo.', price: 30, symbol: '📓', colors: ['#FFC778','#FF978D','#A4DACC'], available: true },
  { id: 'cover-vinyle', category: 'cover', title: 'Pochette vinyle', description: 'Un disque sur fond lavande pour les projets sans photo.', price: 40, symbol: '💿', colors: ['#D4C0F1','#2C2640'], available: true },
  { id: 'profile-etoiles', category: 'profile', title: 'Cadre étoilé', description: 'Un cadre et des étoiles autour de Minuton dans ton profil.', price: 30, symbol: '⭐', colors: ['#FFE7A3','#FFCA60'], available: true },
  { id: 'profile-fleurs', category: 'profile', title: 'Cadre fleuri', description: 'Un cadre végétal pour décorer ton profil.', price: 30, symbol: '🌸', colors: ['#DCECCB','#F7B9CA'], available: true },
  { id: 'palette-pastel', category: 'palette', title: 'Pastel', description: 'Six nouvelles couleurs disponibles sur la feuille de dessin.', price: 30, symbol: '🖌️', colors: ['#685D75','#F3A4B5','#A7C8F2','#AAD5B0','#F3D58E','#C8B2E8'], available: true },
  { id: 'palette-vintage', category: 'palette', title: 'Vintage', description: 'Six teintes chaudes pour tes prochains dessins.', price: 30, symbol: '🖌️', colors: ['#453D32','#B85C47','#548392','#81936D','#D2A450','#947784'], available: true },
  { id: 'palette-ocean', category: 'palette', title: 'Océan', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#183B56', '#2389A8', '#65C9CF', '#B4E8D8', '#F3E4BB', '#557AB5'], available: true },
  { id: 'palette-neon', category: 'palette', title: 'Néon', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#242044', '#ED5EC8', '#8B6DFF', '#47E3D0', '#D8FF68', '#FF9675'], available: true },
  { id: 'palette-terre', category: 'palette', title: 'Terre cuite', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#573B35', '#C77556', '#E5AC80', '#F0D8AD', '#8C9872', '#B39187'], available: true },
  { id: 'palette-sakura', category: 'palette', title: 'Sakura', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#594362', '#E58CAC', '#F7BDCB', '#D2B6E5', '#A9CDB8', '#FFE2B3'], available: true },
  { id: 'palette-foret', category: 'palette', title: 'Forêt', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#253B31', '#45775B', '#85A76B', '#C6D5A3', '#D4B77C', '#8A6A50'], available: true },
  { id: 'palette-bonbon', category: 'palette', title: 'Bonbon', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#704782', '#FF8BB0', '#FFBE85', '#FAE68C', '#8DDDCF', '#A6B7F5'], available: true },
  { id: 'palette-cosmos', category: 'palette', title: 'Cosmos', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#272642', '#5B4E9B', '#9581D1', '#D49EC4', '#80BAD5', '#F4CD87'], available: true },
  { id: 'palette-monochrome', category: 'palette', title: 'Graphite', description: 'Six couleurs coordonnées à utiliser directement sur ta feuille de dessin.', price: 45, symbol: '🖌️', colors: ['#20232B', '#444957', '#6C7280', '#979CA7', '#C9CDD4', '#F1F2F5'], available: true },
  { id: 'cover-ocean', category: 'cover', title: 'Vagues océanes', description: 'Une couverture illustrée pour personnaliser tes projets sans photo.', price: 45, symbol: '📓', colors: ['#70C8D1', '#256880', '#D2EEE6'], available: true },
  { id: 'cover-sakura', category: 'cover', title: 'Carnet Sakura', description: 'Une couverture illustrée pour personnaliser tes projets sans photo.', price: 45, symbol: '📓', colors: ['#F3BDCE', '#C49BD5', '#FFE6CE'], available: true },
  { id: 'cover-cosmos', category: 'cover', title: 'Carnet cosmique', description: 'Une couverture illustrée pour personnaliser tes projets sans photo.', price: 45, symbol: '📓', colors: ['#8E8BD5', '#D4B1E7', '#ACE0E8'], available: true },
  { id: 'cover-soleil', category: 'cover', title: 'Carnet solaire', description: 'Une couverture illustrée pour personnaliser tes projets sans photo.', price: 45, symbol: '📓', colors: ['#FFD281', '#EB967A', '#FFF0BD'], available: true },
  { id: 'cover-foret', category: 'cover', title: 'Carnet botanique', description: 'Une couverture illustrée pour personnaliser tes projets sans photo.', price: 45, symbol: '📓', colors: ['#95BEA0', '#D6DDA2', '#6A9484'], available: true },
  { id: 'cover-neon', category: 'cover', title: 'Carnet électrique', description: 'Une couverture illustrée pour personnaliser tes projets sans photo.', price: 45, symbol: '📓', colors: ['#B69AF4', '#71DCCF', '#F2A7D4'], available: true },
  { id: 'mascot-basket', category: 'mascot', title: 'Minuton basket', description: 'Un maillot violet, un bandeau et un ballon orange. Une tenue visible sur ta mascotte après activation.', price: 70, symbol: '🏅', colors: ['#C7B8FA', '#FFBE83'], available: true, mascotGroup: 'sports' },
  { id: 'mascot-judo', category: 'mascot', title: 'Minuton judoka', description: 'Un judogi blanc et une ceinture noire. Une tenue visible sur ta mascotte après activation.', price: 70, symbol: '🏅', colors: ['#E6EAF2', '#BCD8EC'], available: true, mascotGroup: 'sports' },
  { id: 'mascot-equitation', category: 'mascot', title: 'Minuton cavalier', description: 'Une bombe, une veste et une cravache de cavalier. Une tenue visible sur ta mascotte après activation.', price: 80, symbol: '🏅', colors: ['#CDBB9C', '#EDE0C5'], available: true, mascotGroup: 'sports' },
  { id: 'mascot-football', category: 'mascot', title: 'Minuton footballeur', description: 'Un maillot vert et un ballon de football. Une tenue visible sur ta mascotte après activation.', price: 65, symbol: '🏅', colors: ['#BCE2BA', '#F0EABD'], available: true, mascotGroup: 'sports' },
  { id: 'mascot-tennis', category: 'mascot', title: 'Minuton tennisman', description: 'Une visière et une raquette pour entrer sur le court. Une tenue visible sur ta mascotte après activation.', price: 70, symbol: '🏅', colors: ['#D4EDA3', '#C0E5E1'], available: false },
  { id: 'mascot-boxe', category: 'mascot', title: 'Minuton boxeur', description: 'Deux gants rouges et un bandeau de champion. Une tenue visible sur ta mascotte après activation.', price: 75, symbol: '🏅', colors: ['#F2AAA5', '#FFD5AB'], available: false },
  { id: 'mascot-natation', category: 'mascot', title: 'Minuton nageur', description: 'Un bonnet bleu et des lunettes de natation. Une tenue visible sur ta mascotte après activation.', price: 60, symbol: '🏅', colors: ['#A3D9EF', '#C8EFE6'], available: false },
  { id: 'mascot-cyclisme', category: 'mascot', title: 'Minuton cycliste', description: 'Un casque rayé et un maillot de cycliste. Une tenue visible sur ta mascotte après activation.', price: 75, symbol: '🏅', colors: ['#FFE1A5', '#B3DADB'], available: false },
  { id: 'mascot-rugby', category: 'mascot', title: 'Minuton rugbyman', description: 'Un maillot bordeaux et un ballon ovale. Une tenue visible sur ta mascotte après activation.', price: 70, symbol: '🏅', colors: ['#DCB0C4', '#F3DCB7'], available: false },
  { id: 'mascot-baseball', category: 'mascot', title: 'Minuton baseballeur', description: 'Une casquette, une batte et une balle cousue. Une tenue visible sur ta mascotte après activation.', price: 70, symbol: '🏅', colors: ['#BDD2F4', '#F2D2B1'], available: false },
  { id: 'mascot-ski', category: 'mascot', title: 'Minuton skieur', description: 'Un bonnet, un masque et deux skis. Une tenue visible sur ta mascotte après activation.', price: 80, symbol: '🏅', colors: ['#CADAF7', '#EBD4F1'], available: false },
  { id: 'mascot-skate', category: 'mascot', title: 'Minuton skateur', description: 'Une casquette retournée et un skateboard. Une tenue visible sur ta mascotte après activation.', price: 75, symbol: '🏅', colors: ['#B9E3CE', '#D9C3F0'], available: false },
  {"id": "mascot-basketteuse", "category": "mascot", "title": "Minuton basketteuse", "description": "Un maillot violet, une queue de cheval et un ballon de basket. Une tenue visible sur ta mascotte après activation.", "price": 70, "symbol": "🏅", "colors": ["#C7B8FA", "#FFBE83"], "available": true, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-1.webp", "width": 1254, "height": 1254, "viewBox": [45, 54, 358, 368]}},
  {"id": "mascot-judoka-f", "category": "mascot", "title": "Minuton judoka · féminine", "description": "Une coupe courte, un bandeau discret et un judogi blanc à ceinture noire. Une tenue visible sur ta mascotte après activation.", "price": 70, "symbol": "🏅", "colors": ["#E6EAF2", "#BCD8EC"], "available": true, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-1.webp", "width": 1254, "height": 1254, "viewBox": [475, 68, 308, 350]}},
  {"id": "mascot-footballeuse", "category": "mascot", "title": "Minuton footballeuse", "description": "Un maillot vert et un ballon pour entrer sur le terrain. Une tenue visible sur ta mascotte après activation.", "price": 65, "symbol": "🏅", "colors": ["#BCE2BA", "#F0EABD"], "available": true, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-1.webp", "width": 1254, "height": 1254, "viewBox": [882, 64, 332, 366]}},
  {"id": "mascot-tenniswoman", "category": "mascot", "title": "Minuton tenniswoman", "description": "Une visière blanche, une raquette violette et une balle de tennis. Une tenue visible sur ta mascotte après activation.", "price": 70, "symbol": "🏅", "colors": ["#D4EDA3", "#C0E5E1"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-1.webp", "width": 1254, "height": 1254, "viewBox": [26, 452, 395, 374]}},
  {"id": "mascot-boxeuse", "category": "mascot", "title": "Minuton boxeuse", "description": "Une tenue rouge, deux gants et un bandeau de championne. Une tenue visible sur ta mascotte après activation.", "price": 75, "symbol": "🏅", "colors": ["#F2AAA5", "#FFD5AB"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-1.webp", "width": 1254, "height": 1254, "viewBox": [468, 447, 350, 365]}},
  {"id": "mascot-cavaliere", "category": "mascot", "title": "Minuton cavalière", "description": "Une bombe, une veste bleu nuit et des bottes pour monter à cheval. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🏅", "colors": ["#CDBB9C", "#EDE0C5"], "available": true, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-1.webp", "width": 1254, "height": 1254, "viewBox": [902, 446, 329, 387]}},
  {"id": "mascot-athena", "category": "mascot", "title": "Minuton Athéna", "description": "Un casque grec, une cape prune et un bouclier à la chouette. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-1.webp", "width": 1254, "height": 1254, "viewBox": [455, 843, 381, 354]}},
  {"id": "mascot-nageuse", "category": "mascot", "title": "Minuton nageuse", "description": "Un bonnet bleu et des lunettes pour plonger dans tes activités. Une tenue visible sur ta mascotte après activation.", "price": 60, "symbol": "🏅", "colors": ["#A3D9EF", "#C8EFE6"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-2.webp", "width": 1254, "height": 1254, "viewBox": [43, 57, 352, 350]}},
  {"id": "mascot-cycliste-f", "category": "mascot", "title": "Minuton cycliste · féminine", "description": "Un casque turquoise, un maillot et une queue de cheval. Une tenue visible sur ta mascotte après activation.", "price": 75, "symbol": "🏅", "colors": ["#FFE1A5", "#B3DADB"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-2.webp", "width": 1254, "height": 1254, "viewBox": [476, 60, 327, 346]}},
  {"id": "mascot-rugbywoman", "category": "mascot", "title": "Minuton rugbywoman", "description": "Un maillot bordeaux et un ballon ovale, prête pour le match. Une tenue visible sur ta mascotte après activation.", "price": 70, "symbol": "🏅", "colors": ["#DCB0C4", "#F3DCB7"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-2.webp", "width": 1254, "height": 1254, "viewBox": [878, 60, 326, 347]}},
  {"id": "mascot-baseballeuse", "category": "mascot", "title": "Minuton baseballeuse", "description": "Une casquette, une batte et une balle cousue. Une tenue visible sur ta mascotte après activation.", "price": 70, "symbol": "🏅", "colors": ["#BDD2F4", "#F2D2B1"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-2.webp", "width": 1254, "height": 1254, "viewBox": [28, 462, 389, 358]}},
  {"id": "mascot-skieuse", "category": "mascot", "title": "Minuton skieuse", "description": "Une tenue violette, un masque, deux bâtons et des skis. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🏅", "colors": ["#CADAF7", "#EBD4F1"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-2.webp", "width": 1254, "height": 1254, "viewBox": [441, 461, 378, 365]}},
  {"id": "mascot-skateuse", "category": "mascot", "title": "Minuton skateuse", "description": "Une casquette retournée et un skateboard turquoise. Une tenue visible sur ta mascotte après activation.", "price": 75, "symbol": "🏅", "colors": ["#B9E3CE", "#D9C3F0"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-2.webp", "width": 1254, "height": 1254, "viewBox": [874, 460, 361, 366]}},
  {"id": "mascot-poney", "category": "mascot", "title": "Minuton à poney", "description": "Une cavalière sur un petit poney alezan à la crinière claire. Une tenue visible sur ta mascotte après activation.", "price": 110, "symbol": "🏅", "colors": ["#D9B18A", "#B7C9E7"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-sports-2.webp", "width": 1254, "height": 1254, "viewBox": [428, 843, 409, 377]}},
  {"id": "mascot-danseuse", "category": "mascot", "title": "Minuton danseuse", "description": "Un tutu lavande et des chaussons pour créer en mouvement. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "✨", "colors": ["#D5BEF5", "#FFE8CB"], "available": true, "mascotGroup": "arts", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-creative.webp", "width": 1536, "height": 1024, "viewBox": [94, 68, 396, 429]}},
  {"id": "mascot-surfeuse", "category": "mascot", "title": "Minuton surfeuse", "description": "Une tenue turquoise et une planche corail pour prendre la vague. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🏅", "colors": ["#A6DEDC", "#F6B19E"], "available": false, "mascotGroup": "sports", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-creative.webp", "width": 1536, "height": 1024, "viewBox": [564, 78, 450, 415]}},
  {"id": "mascot-astronaute-f", "category": "mascot", "title": "Minuton astronaute · féminine", "description": "Une combinaison blanche et un casque pour explorer les étoiles. Une tenue visible sur ta mascotte après activation.", "price": 100, "symbol": "✨", "colors": ["#DAD4F5", "#B8D9F4"], "available": false, "mascotGroup": "adventure", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-creative.webp", "width": 1536, "height": 1024, "viewBox": [1060, 60, 394, 441]}},
  {"id": "mascot-sorciere", "category": "mascot", "title": "Minuton sorcière", "description": "Un chapeau prune, un balai et une baguette étoilée. Une tenue visible sur ta mascotte après activation.", "price": 100, "symbol": "✨", "colors": ["#C8A1DF", "#A8CBA9"], "available": false, "mascotGroup": "adventure", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-creative.webp", "width": 1536, "height": 1024, "viewBox": [82, 519, 464, 449]}},
  {"id": "mascot-exploratrice", "category": "mascot", "title": "Minuton exploratrice", "description": "Une tresse, un chapeau et une boussole pour partir à l’aventure. Une tenue visible sur ta mascotte après activation.", "price": 90, "symbol": "✨", "colors": ["#BECB9D", "#E5C69E"], "available": false, "mascotGroup": "adventure", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-creative.webp", "width": 1536, "height": 1024, "viewBox": [566, 533, 417, 433]}},
  {"id": "mascot-cheffe", "category": "mascot", "title": "Minuton cheffe", "description": "Une toque, un tablier et un bol pour préparer tes nouvelles idées. Une tenue visible sur ta mascotte après activation.", "price": 75, "symbol": "✨", "colors": ["#C1DDD0", "#FFE3C6"], "available": false, "mascotGroup": "arts", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-female-creative.webp", "width": 1536, "height": 1024, "viewBox": [1043, 513, 417, 455]}},
  {"id": "mascot-halloween-vampire", "category": "mascot", "title": "Minuton vampire", "description": "Une cape prune doublée de rouge, deux petites canines et un seau de bonbons. Une tenue Halloween visible après activation.", "price": 90, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [7, 22, 457, 414]}},
  {"id": "mascot-halloween-sorcier", "category": "mascot", "title": "Minuton sorcier", "description": "Un chapeau vert, un grimoire et un bâton magique. Une tenue Halloween visible après activation.", "price": 100, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [478, 23, 409, 411]}},
  {"id": "mascot-halloween-citrouille", "category": "mascot", "title": "Minuton citrouille", "description": "Un costume de citrouille orange et un panier rempli de bonbons. Une tenue Halloween visible après activation.", "price": 75, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [909, 46, 408, 390]}},
  {"id": "mascot-halloween-fantome", "category": "mascot", "title": "Minuton fantôme", "description": "Une cape ivoire, un nœud prune et une lanterne. Une tenue Halloween visible après activation.", "price": 75, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [1320, 27, 432, 409]}},
  {"id": "mascot-halloween-vampiresse", "category": "mascot", "title": "Minuton vampiresse", "description": "Un carré sombre, une cape rouge et prune et un petit panier de bonbons. Une tenue Halloween visible après activation.", "price": 90, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [11, 444, 408, 423]}, "mascotGender": "female"},
  {"id": "mascot-halloween-sorciere", "category": "mascot", "title": "Minuton sorcière Halloween", "description": "Un chapeau vert, une tresse et une baguette étoilée avec son balai. Une tenue Halloween visible après activation.", "price": 100, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [475, 442, 438, 429]}, "mascotGender": "female"},
  {"id": "mascot-halloween-citrouille-f", "category": "mascot", "title": "Minuton citrouille fleurie", "description": "Une coiffure rousse, une feuille verte et un costume de citrouille. Une tenue Halloween visible après activation.", "price": 75, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [926, 452, 388, 416]}, "mascotGender": "female"},
  {"id": "mascot-halloween-fantome-f", "category": "mascot", "title": "Minuton fantôme malicieuse", "description": "Une cape ivoire, des boucles rousses et un ruban lavande avec une lanterne. Une tenue Halloween visible après activation.", "price": 75, "symbol": "🎃", "colors": ["#F2BA79", "#B9A0E3"], "available": true, "mascotGroup": "halloween", "mascotArt": {"src": "/art/minuton-halloween.webp", "width": 1774, "height": 887, "viewBox": [1334, 446, 424, 421]}, "mascotGender": "female"},
  {"id": "mascot-photographe", "category": "mascot", "title": "Minuton photographe", "description": "Un appareil photo, une veste sauge et une sacoche pour capturer tes idées. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🎨", "colors": ["#D5BEF5", "#FFE8CB"], "available": true, "mascotGroup": "arts", "mascotArt": {"src": "/art/minuton-arts-v1.webp", "width": 1536, "height": 1024, "viewBox": [107, 11, 357, 449]}},
  {"id": "mascot-cineaste", "category": "mascot", "title": "Minuton cinéaste", "description": "Une casquette retournée, un clap et un storyboard pour imaginer tes films. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🎨", "colors": ["#D5BEF5", "#FFE8CB"], "available": true, "mascotGroup": "arts", "mascotArt": {"src": "/art/minuton-arts-v1.webp", "width": 1536, "height": 1024, "viewBox": [557, 11, 452, 452]}},
  {"id": "mascot-violoniste", "category": "mascot", "title": "Minuton violoniste", "description": "Un violon, un archet et une tenue lavande pour faire vibrer tes mélodies. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🎨", "colors": ["#D5BEF5", "#FFE8CB"], "available": true, "mascotGroup": "arts", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-arts-v1.webp", "width": 1536, "height": 1024, "viewBox": [1061, 16, 474, 472]}},
  {"id": "mascot-dj", "category": "mascot", "title": "Minuton DJ", "description": "Un casque lavande, un sweat turquoise et des platines pour composer ton rythme. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🎨", "colors": ["#D5BEF5", "#FFE8CB"], "available": true, "mascotGroup": "arts", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-arts-v1.webp", "width": 1536, "height": 1024, "viewBox": [53, 486, 446, 493]}},
  {"id": "mascot-ecrivaine", "category": "mascot", "title": "Minuton écrivaine", "description": "Une tresse rousse, des lunettes dorées et un carnet pour donner vie à tes histoires. Une tenue visible sur ta mascotte après activation.", "price": 80, "symbol": "🎨", "colors": ["#D5BEF5", "#FFE8CB"], "available": true, "mascotGroup": "arts", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-arts-v1.webp", "width": 1536, "height": 1024, "viewBox": [556, 482, 455, 504]}},
  {"id": "mascot-zeus", "category": "mascot", "title": "Minuton Zeus", "description": "Une couronne de laurier, une cape prune et la foudre du roi de l’Olympe. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotArt": {"src": "/art/minuton-olympus-v1.webp", "width": 1774, "height": 887, "viewBox": [15, 14, 449, 419]}},
  {"id": "mascot-poseidon", "category": "mascot", "title": "Minuton Poséidon", "description": "Un trident doré, une cape marine et un coquillage pour le dieu des mers. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotArt": {"src": "/art/minuton-olympus-v1.webp", "width": 1774, "height": 887, "viewBox": [464, 10, 442, 423]}},
  {"id": "mascot-apollon", "category": "mascot", "title": "Minuton Apollon", "description": "Une lyre, une couronne de laurier et une cape solaire pour le dieu des arts. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotArt": {"src": "/art/minuton-olympus-v1.webp", "width": 1774, "height": 887, "viewBox": [906, 22, 403, 416]}},
  {"id": "mascot-hermes", "category": "mascot", "title": "Minuton Hermès", "description": "Un casque et des sandales ailés, avec le caducée du messager des dieux. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotArt": {"src": "/art/minuton-olympus-v1.webp", "width": 1774, "height": 887, "viewBox": [1326, 20, 447, 418]}},
  {"id": "mascot-hera", "category": "mascot", "title": "Minuton Héra", "description": "Un diadème précieux, une cape prune et un sceptre au paon pour la reine de l’Olympe. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-olympus-v1.webp", "width": 1774, "height": 887, "viewBox": [36, 450, 394, 423]}},
  {"id": "mascot-artemis", "category": "mascot", "title": "Minuton Artémis", "description": "Un croissant de lune, un arc et une cape verte pour la déesse de la chasse. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-olympus-v1.webp", "width": 1774, "height": 887, "viewBox": [458, 457, 395, 416]}},
  {"id": "mascot-aphrodite", "category": "mascot", "title": "Minuton Aphrodite", "description": "Une couronne de perles, une rose et un coquillage pour la déesse de l’amour. Une tenue visible sur ta mascotte après activation.", "price": 120, "symbol": "✨", "colors": ["#D9AC58", "#DAC3E5"], "available": true, "mascotGroup": "olympus", "mascotGender": "female", "mascotArt": {"src": "/art/minuton-olympus-v1.webp", "width": 1774, "height": 887, "viewBox": [924, 450, 385, 423]}},
]
export function getShopItem(id: string): ShopItem | undefined { return SHOP_ITEMS.find((item) => item.id === id) }
export interface ShopState {
  /** Crédit de test distinct des minutons gagnés avec les activités. */
  bonus?: number
  canClaimTestCredit?: boolean
  earned: number
  spent: number
  balance: number
  owned: string[]
  equipped: Partial<Record<ShopCategory, string>>
}
